### ISSUE TITLE
testing on single image

### ISSUE THREAD

**Issue by mahilaMoghadami** [Ranchosky/OAN#1]
hello
Thanks for your  implementation sharing
how can I test single image with this implementation, without training model. are you shared your models ? if yes, where?
thank you.

**Comment by zhangpeng2001** [comment]
Thank you for your advice, we have uploaded the trained models. you can use the trained models(in the Inference part) to test a single image.

**Comment by mahilaMoghadami** [comment]
thank you.
Can I have any one implementation team email?

**Comment by zhangpeng2001** [comment]
@mahilaMoghadami iampengzhang@mail.nwpu.edu.cn

**Comment by mahilaMoghadami** [comment]
which .py file is for testing on single image? 
if huge_image_demo.py  what is 'split' in parser argument?
and also where I should set out_file?

**Comment by zhangpeng2001** [comment]
@mahilaMoghadami we have update the inference part about your problem.

**Comment by mahilaMoghadami** [comment]
thank you

I have an error for testing and according to checks I did I found it:
you pass 'out_file' to  'show_result_pyplot' function for mmdetection. but as I check this function in OAN/mmdet/apis/inference.py address, it doesn't get 'out_file'. it seems mmdetection in your project folder is not updated.

this is 'show_result_pyplot' function in your project:
https://github.com/Ranchosky/OAN/blob/main/mmdet/apis/inference.py

and this is  'show_result_pyplot' in mmdetection:
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/inference.py


which are different in input arguments.

**Comment by zhangpeng2001** [comment]
@mahilaMoghadami oh, so sorry. i forgot to change the inference.py. thank you for your rectify.

**Comment by mahilaMoghadami** [comment]
thanks for your attention
but still there is error :
" /content/OAN/mmdet/models/detectors/obb/obb_base.py:72: UserWarning: show==False and out_file is not specified, only result image will be returned
  warnings.warn('show==False and out_file is not specified, only '
Figure(1500x1000)"

it seems detection result is ready but outfile has error.
Im using 'huge_image_demo.py'

**Comment by mahilaMoghadami** [comment]
thank you.
yes, now it works great.
